# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-monkill" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "f57f90958d175abb0e470e91d6c9547129dc6bd47690293039921e8d7e765281"
      url "https://github.com/jtprogru/go-monkill/releases/download/v#{version}/go-monkill_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8f6abb207d427e3d2b3125e9dadcb2020441ae8b078eb9ec09951a96c143fcd7"
      url "https://github.com/jtprogru/go-monkill/releases/download/v#{version}/go-monkill_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d226905c70c4e7d6bcc33ea5a8969a075af2359ed2a7fc3ad558dc57335be3b8"
      url "https://github.com/jtprogru/go-monkill/releases/download/v#{version}/go-monkill_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6d35e5d16833a67c35f5655cd84bb223655a0bd7a9be570065bdab7455cccd53"
      url "https://github.com/jtprogru/go-monkill/releases/download/v#{version}/go-monkill_Linux_arm64.tar.gz"
    end
  end

  name "go-monkill"
  desc "Run a command after a process with a given PID terminates"
  homepage "https://github.com/jtprogru/go-monkill"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-monkill"
  bash_completion "completions/go-monkill.bash"
  fish_completion "completions/go-monkill.fish"
  zsh_completion "completions/go-monkill.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-monkill"]
    end
  end

  # No zap stanza required

end
