# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-monkill" do
  version "1.1.0"

  on_macos do
    on_arm do
      sha256 "ef41a9e7e43028b4baf2e6030cca3f585f5bc2d005df23e66e5f55522d57c36b"
      url "https://github.com/jtprogru/go-monkill/releases/download/v#{version}/go-monkill_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "454fbefe85614a513ef9146128f4d06ef2f57626767f57d3821e902b3126edc0"
      url "https://github.com/jtprogru/go-monkill/releases/download/v#{version}/go-monkill_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5638be761efa20becc6b5501fc245ef98cafaafbd86f6dfd8a71225ea0a2b733"
      url "https://github.com/jtprogru/go-monkill/releases/download/v#{version}/go-monkill_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "937a18dcd91861702975b95427f6324051b8a3104ccfc700d79a8155d7114810"
      url "https://github.com/jtprogru/go-monkill/releases/download/v#{version}/go-monkill_Linux_x86_64.tar.gz"
    end
  end

  name "go-monkill"
  desc "Run a command after a process with a given PID terminates"
  homepage "https://github.com/jtprogru/go-monkill"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-monkill"
  bash_completion "completions/go-monkill.bash"
  fish_completion "completions/go-monkill.fish"
  zsh_completion "completions/go-monkill.zsh"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/go-monkill"]
  end

  # No zap stanza required
end
