# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-monkill" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "093a85c8351dd81e965d1f06be865e41bc2bb34360e3f0f93c46138b4c3e4ac5"
      url "https://github.com/jtprogru/go-monkill/releases/download/v#{version}/go-monkill_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "be352542a3e6f63a2839ab8adf89ea16cb303c561b20d4e7ec70ac8c32b4eb24"
      url "https://github.com/jtprogru/go-monkill/releases/download/v#{version}/go-monkill_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e15e4eebdbc42180d28ab9b3f2cee4a973dd1582c57cf79c787246c62b692336"
      url "https://github.com/jtprogru/go-monkill/releases/download/v#{version}/go-monkill_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "0dc2b1def141559b56630e9e9f0dd7feb6256ef2298d2e9e47dcef2da25e02da"
      url "https://github.com/jtprogru/go-monkill/releases/download/v#{version}/go-monkill_Linux_arm64.tar.gz"
    end
  end

  name "go-monkill"
  desc "Run a command after a process with a given PID terminates"
  homepage "https://github.com/jtprogru/go-monkill"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-monkill"
  bash_completion "completions/go-monkill.bash"
  fish_completion "completions/go-monkill.fish"
  zsh_completion "completions/go-monkill.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-monkill"]
    end
  end

  # No zap stanza required

end
