# This file was generated by GoReleaser. DO NOT EDIT.
cask "indexnow" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "8044b5a0c23140bb9f7aaf81b35c1cc8a1c2d16cf36d4054692bd14e35345cb5"
      url "https://github.com/jtprogru/indexnow/releases/download/v#{version}/indexnow_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "16df6ae121e3ca4cd86e942087fb3be591363441157b81c2b6441742cd0dcd3b"
      url "https://github.com/jtprogru/indexnow/releases/download/v#{version}/indexnow_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5e303ff690f01267605403c30f85fa605f0e11393df158fc8e98ab3294c35d2b"
      url "https://github.com/jtprogru/indexnow/releases/download/v#{version}/indexnow_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8e4805e2802e7f9f1076581d35b702310844744a3f2045f7d04521db2f9b41fa"
      url "https://github.com/jtprogru/indexnow/releases/download/v#{version}/indexnow_Linux_arm64.tar.gz"
    end
  end

  name "indexnow"
  desc "IndexNow protocol client for content pipelines"
  homepage "https://github.com/jtprogru/indexnow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "indexnow"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/indexnow"]
    end
  end

  # No zap stanza required

end
