# This file was generated by GoReleaser. DO NOT EDIT.
cask "indexnow" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "025d9eeb065e950fe6e077c4ac8c6fec43f286e7753b5f7cb9c1337dd9053d74"
      url "https://github.com/jtprogru/indexnow/releases/download/v#{version}/indexnow_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c3d579cabbea3111a0a533154cdeefc56c55340a4cc4bc99ef58044bca0c97dc"
      url "https://github.com/jtprogru/indexnow/releases/download/v#{version}/indexnow_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d7e151e7da13bbbee08607ceda79dd93ad2003649844f905f087ce82167800f2"
      url "https://github.com/jtprogru/indexnow/releases/download/v#{version}/indexnow_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7ad69bb5caac3d8eef41f62898a2f4dbfb1ebc8f70d727042472253b08d38a9c"
      url "https://github.com/jtprogru/indexnow/releases/download/v#{version}/indexnow_Linux_arm64.tar.gz"
    end
  end

  name "indexnow"
  desc "IndexNow protocol client for content pipelines"
  homepage "https://github.com/jtprogru/indexnow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "indexnow"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/indexnow"]
    end
  end

  # No zap stanza required

end
