# This file was generated by GoReleaser. DO NOT EDIT.
cask "indexnow" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "601b305ee509a8c5efab9c5f1cc2c573d9a9c87602e7e82ac37cf0952aa38c02"
      url "https://github.com/jtprogru/indexnow/releases/download/v#{version}/indexnow_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "16ebf435fdfb430d7b61b01d667becff35292e95cbb266e506c568e3726d2082"
      url "https://github.com/jtprogru/indexnow/releases/download/v#{version}/indexnow_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4194f2275ce7bffc1038bd44a63bcd88a70360eac30811f22bd990d22caa7c78"
      url "https://github.com/jtprogru/indexnow/releases/download/v#{version}/indexnow_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ef3c8d671430e038688c4985c09ddf8b70c4af66b62503e243af94a2efba15fc"
      url "https://github.com/jtprogru/indexnow/releases/download/v#{version}/indexnow_Linux_arm64.tar.gz"
    end
  end

  name "indexnow"
  desc "IndexNow protocol client for content pipelines"
  homepage "https://github.com/jtprogru/indexnow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "indexnow"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/indexnow"]
    end
  end

  # No zap stanza required

end
