# This file was generated by GoReleaser. DO NOT EDIT.
cask "jtgpwgen" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "74d489c6158c778144b126a1f3db44c2d6dd09b4b6ed42c04052f4a0c96cde39"
      url "https://github.com/jtprogru/jtgpwgen/releases/download/v#{version}/jtgpwgen_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/jtprogru/jtgpwgen"
    end
    on_arm do
      sha256 "0283b54a99a47cca1b59c3a4844922ad4cc218ef20840f340bf277dff664e0ca"
      url "https://github.com/jtprogru/jtgpwgen/releases/download/v#{version}/jtgpwgen_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/jtprogru/jtgpwgen"
    end
  end

  on_linux do
    on_intel do
      sha256 "aae17cc49213217364759485c1a4aeb3595d25b1d2d5832eab01b7b89fb94bce"
      url "https://github.com/jtprogru/jtgpwgen/releases/download/v#{version}/jtgpwgen_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/jtprogru/jtgpwgen"
    end
    on_arm do
      sha256 "8fcf3654e9bf1fc7b738d0d264dc692c162a87ba9db6c4a474979f354e5b4d76"
      url "https://github.com/jtprogru/jtgpwgen/releases/download/v#{version}/jtgpwgen_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/jtprogru/jtgpwgen"
    end
  end

  name "jtgpwgen"
  desc "Password generator with configurable character classes and memorable mode"
  homepage "https://github.com/jtprogru/jtgpwgen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jtgpwgen"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jtgpwgen"]
    end
  end

  # No zap stanza required

end
