# This file was generated by GoReleaser. DO NOT EDIT.
cask "jtgpwgen" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "88b8b7ab4cd46bd4599ecb738f739019800e317caee88fb38913449d2dd821cf"
      url "https://github.com/jtprogru/jtgpwgen/releases/download/v#{version}/jtgpwgen_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/jtprogru/jtgpwgen"
    end
    on_arm do
      sha256 "7eb0805e944bdf4f64d54e95c44ec0cd252ea43fbb686761e8fb25204a6a57c9"
      url "https://github.com/jtprogru/jtgpwgen/releases/download/v#{version}/jtgpwgen_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/jtprogru/jtgpwgen"
    end
  end

  on_linux do
    on_intel do
      sha256 "b8a97f5ab49bd36d3abb13bd4d485917bbbc5da441fdcd1a13c695f41f6a392f"
      url "https://github.com/jtprogru/jtgpwgen/releases/download/v#{version}/jtgpwgen_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/jtprogru/jtgpwgen"
    end
    on_arm do
      sha256 "c72b607775c16db569ca3127bd190189e3b3282fd3f9a67492338945a8c98155"
      url "https://github.com/jtprogru/jtgpwgen/releases/download/v#{version}/jtgpwgen_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/jtprogru/jtgpwgen"
    end
  end

  name "jtgpwgen"
  desc "Password generator with configurable character classes and memorable mode"
  homepage "https://github.com/jtprogru/jtgpwgen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jtgpwgen"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jtgpwgen"]
    end
  end

  # No zap stanza required

end
