# This file was generated by GoReleaser. DO NOT EDIT.
cask "jtgpwgen" do
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/jtgpwgen"]
  end

  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "c580ddf3b31c5266437f56e3a14e1b7777175821d9be53524e57351efbedc0e2"
      url "https://github.com/jtprogru/jtgpwgen/releases/download/v#{version}/jtgpwgen_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "469b27cf0388df44daed6585b7ead8bcd519ad1e6ddca916de51b1501301829f"
      url "https://github.com/jtprogru/jtgpwgen/releases/download/v#{version}/jtgpwgen_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "314b9ab36f3ea1ac5f3aac019372b9c6cc26694c9cf9aabb0f1ef0d9e87d1090"
      url "https://github.com/jtprogru/jtgpwgen/releases/download/v#{version}/jtgpwgen_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "85723aed6cbb82ead3bb4b5b4c95ee68ab65cca54657b356817ed17dc80db7e9"
      url "https://github.com/jtprogru/jtgpwgen/releases/download/v#{version}/jtgpwgen_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "jtgpwgen"
  desc "Password generator with configurable character classes and memorable mode"
  homepage "https://github.com/jtprogru/jtgpwgen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jtgpwgen"

  # No zap stanza required

end
