# This file was generated by GoReleaser. DO NOT EDIT.
cask "jtsekret" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "5f8a4036e215afd28def2b8456bfb3ec5fb64f89c7215d775f4e0c1b02e5874e"
      url "https://github.com/jtprogru/jtsekret/releases/download/v#{version}/jtsekret_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7bff49c77467cb4756e7deff21d5da0cdc031ce18164d6157ece85800996c16f"
      url "https://github.com/jtprogru/jtsekret/releases/download/v#{version}/jtsekret_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ef8140d3c882e0f2fb0c58dc811c198ba3850da1e3b2e5edc5f924effca4204c"
      url "https://github.com/jtprogru/jtsekret/releases/download/v#{version}/jtsekret_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "594c6b8b50794f741bf4a5c50e38eb38ef247733f7cc256e4254b0ac1bccf6ad"
      url "https://github.com/jtprogru/jtsekret/releases/download/v#{version}/jtsekret_Linux_arm64.tar.gz"
    end
  end

  name "jtsekret"
  desc "CLI for personal secrets management with pluggable backends."
  homepage "https://github.com/jtprogru/jtsekret"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jtsekret"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jtsekret"]
    end
  end

  # No zap stanza required

end
