# This file was generated by GoReleaser. DO NOT EDIT.
cask "jtsekret" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "44e4f8658649b461cc5eae4108c33c939fe9e6088e5d3e94a52e0ebf7851226e"
      url "https://github.com/jtprogru/jtsekret/releases/download/v#{version}/jtsekret_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "df674699bb692d9b1f5fbcdfc5f776677da4406bd64f04147fdae1e764d93404"
      url "https://github.com/jtprogru/jtsekret/releases/download/v#{version}/jtsekret_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ddb68d21dbca4bb115ee4d86a4b9cfb1ffc218032dab9cfbaf97ff1c520ea01f"
      url "https://github.com/jtprogru/jtsekret/releases/download/v#{version}/jtsekret_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "39bf93b4f7393031f9f5d5834c343edb402a6418a9aa97cf27733a0ad5e11609"
      url "https://github.com/jtprogru/jtsekret/releases/download/v#{version}/jtsekret_Linux_arm64.tar.gz"
    end
  end

  name "jtsekret"
  desc "CLI for personal secrets management with pluggable backends."
  homepage "https://github.com/jtprogru/jtsekret"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jtsekret"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jtsekret"]
    end
  end

  # No zap stanza required

end
