# This file was generated by GoReleaser. DO NOT EDIT.
cask "jtsekret" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "3562ebb80f18bbcc51ea3e34f3fd1fefa3e09c6798dccfb92b9f7b8d16af6cb2"
      url "https://github.com/jtprogru/jtsekret/releases/download/v#{version}/jtsekret_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "12b195694f1519cc2597e4cfffeb2199585dd5232137e6abaf98f49a368de7a1"
      url "https://github.com/jtprogru/jtsekret/releases/download/v#{version}/jtsekret_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f98711cac83bf1e0c9c37b8d2b02b4dc48d056f952689cb8db3c252321f2a457"
      url "https://github.com/jtprogru/jtsekret/releases/download/v#{version}/jtsekret_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8d9c04dfc33a55ee4f00bd4e13822525f15e66e834ede53de10ff452605c9fdb"
      url "https://github.com/jtprogru/jtsekret/releases/download/v#{version}/jtsekret_Linux_arm64.tar.gz"
    end
  end

  name "jtsekret"
  desc "CLI for personal secrets management with pluggable backends."
  homepage "https://github.com/jtprogru/jtsekret"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jtsekret"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jtsekret"]
    end
  end

  # No zap stanza required

end
