# This file was generated by GoReleaser. DO NOT EDIT.
cask "noisy" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "02b85ce2947f2f8580a3236cdcedc750dfd04825c6e9cfdfb428310e07773eb0"
      url "https://github.com/jtprogru/noisy/releases/download/v#{version}/noisy_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bf6ccdda11792e5ae0f16de152d950b40fd34fd91afcdb35fa852989e9abd0a0"
      url "https://github.com/jtprogru/noisy/releases/download/v#{version}/noisy_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ecfb9ef8d45b9a5c28abf02b74bedf556a3e6585ed9d77bc1305e5c8b627a1ec"
      url "https://github.com/jtprogru/noisy/releases/download/v#{version}/noisy_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ddc5c1a3ae3e5f54d47143d5353b66ad8a7997c8ad26cc716df25a17843d0180"
      url "https://github.com/jtprogru/noisy/releases/download/v#{version}/noisy_Linux_arm64.tar.gz"
    end
  end

  name "noisy"
  desc "Random HTTP/DNS traffic noise generator (Go port of 1tayH/noisy)"
  homepage "https://github.com/jtprogru/noisy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "noisy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noisy"]
    end
  end

  # No zap stanza required

end
