# This file was generated by GoReleaser. DO NOT EDIT.
cask "noisy" do
  version "0.2.4"

  on_macos do
    on_arm do
      sha256 "d98e421320032dc54c1137cde70db7dfd54a7b003fda59664fdd950e9c238a3d"
      url "https://github.com/jtprogru/noisy/releases/download/v#{version}/noisy_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "98d188fc4bbb9ad20a1e423f162ced48671da49a02a7a54e8333484e1a0d693d"
      url "https://github.com/jtprogru/noisy/releases/download/v#{version}/noisy_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "90801c91ca2731fd864338c6aafc8c15ab286416d334a8096bf0a3ac4e16e0e1"
      url "https://github.com/jtprogru/noisy/releases/download/v#{version}/noisy_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e940f7e095bd4fe708ea84c455bb35d506bac95b5bad87d22c6b3040b8a1d4f8"
      url "https://github.com/jtprogru/noisy/releases/download/v#{version}/noisy_Linux_x86_64.tar.gz"
    end
  end

  name "noisy"
  desc "Random HTTP/DNS traffic noise generator (Go port of 1tayH/noisy)"
  homepage "https://github.com/jtprogru/noisy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "noisy"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/noisy"]
  end

  # No zap stanza required
end
