# This file was generated by GoReleaser. DO NOT EDIT.
cask "noisy" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "2bbb7e0d2b4098922099efa6a592f631164669f254739da6edc3e7eef0a3dccc"
      url "https://github.com/jtprogru/noisy/releases/download/v#{version}/noisy_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5c2df467a32a2cd862fc921f7e827e6f808699b50a9014f1cb5501b47c7bef34"
      url "https://github.com/jtprogru/noisy/releases/download/v#{version}/noisy_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "012ef15ad6e41e4090f8e67e17efeed7fbbfa42bb80a712fd1e9f94f14d0e8ff"
      url "https://github.com/jtprogru/noisy/releases/download/v#{version}/noisy_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c65efa85e390803d2a3a5be77685434f8107fdb793d73574cadd585c09fcbf98"
      url "https://github.com/jtprogru/noisy/releases/download/v#{version}/noisy_Linux_arm64.tar.gz"
    end
  end

  name "noisy"
  desc "Random HTTP/DNS traffic noise generator (Go port of 1tayH/noisy)"
  homepage "https://github.com/jtprogru/noisy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "noisy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noisy"]
    end
  end

  # No zap stanza required

end
