# This file was generated by GoReleaser. DO NOT EDIT.
cask "repo-opener" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "d5c38ead946bb3d7f113a51b9b0f78f45196342badf40abb0591c015f821e9cd"
      url "https://github.com/jtprogru/repo-opener/releases/download/#{version}/repo-opener_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b636e18d7ce8234a2733014af1e94a4c0505531fde17d6b9ae4afddee29337fb"
      url "https://github.com/jtprogru/repo-opener/releases/download/#{version}/repo-opener_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7590431fe5ae31101c3ac672910ca245f4f15073c34d510b784952d4c0594b4c"
      url "https://github.com/jtprogru/repo-opener/releases/download/#{version}/repo-opener_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f82f86d3c9605044fb582f427602564671891bb13e6723921fa3fcf50372d8ee"
      url "https://github.com/jtprogru/repo-opener/releases/download/#{version}/repo-opener_#{version}_linux_arm64.tar.gz"
    end
  end

  name "repo-opener"
  desc "Print or open the current Git repository's remote URL in a browser"
  homepage "https://github.com/jtprogru/repo-opener"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repo-opener"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/repo-opener"]
    end
  end

  # No zap stanza required

end
