# This file was generated by GoReleaser. DO NOT EDIT.
cask "repo-opener" do
  version "0.5.3"

  on_macos do
    on_intel do
      sha256 "64fe591a9c7fe45cd001cd19a2972537cd3e625f9dfdd5860356ceadecaa2d0c"
      url "https://github.com/jtprogru/repo-opener/releases/download/#{version}/repo-opener_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4f5230320cf58be1fbc02e4fbc15200b76dbb1c970ecf5614453aadbfa81d9b5"
      url "https://github.com/jtprogru/repo-opener/releases/download/#{version}/repo-opener_#{version}_darwin_arm64vv8.0.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4c82912d8e5963540bde079c034c84ec1722e7675f240af51226b3021f21ce48"
      url "https://github.com/jtprogru/repo-opener/releases/download/#{version}/repo-opener_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c36a427da731890af9ddcfcc6b47249f75a7dde44773c9daf165e602eeadf95d"
      url "https://github.com/jtprogru/repo-opener/releases/download/#{version}/repo-opener_#{version}_linux_arm64vv8.0.tar.gz"
    end
  end

  name "repo-opener"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repo-opener"

  # No zap stanza required

end
