# This file was generated by GoReleaser. DO NOT EDIT.
cask "repo-opener" do
  version "0.6.3"

  on_macos do
    on_intel do
      sha256 "564c76fd0b4905c334dd023e9101ac004baac9fe7f7e49abeb7f4a9c5d78fd59"
      url "https://github.com/jtprogru/repo-opener/releases/download/#{version}/repo-opener_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "41b88fdc87c9c66f37f05161c99055a67043bcfa01e7a3247844e7b88fd0c6c4"
      url "https://github.com/jtprogru/repo-opener/releases/download/#{version}/repo-opener_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2cc538adab6542dd6a2e884d32c3d27d06ebf20ef28ea36c3353d20796dfe154"
      url "https://github.com/jtprogru/repo-opener/releases/download/#{version}/repo-opener_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4b4dc2a050064ebc97a2f0d59e932ef2a02e9de05cc7d4e8d3cac9a18122f046"
      url "https://github.com/jtprogru/repo-opener/releases/download/#{version}/repo-opener_#{version}_linux_arm64.tar.gz"
    end
  end

  name "repo-opener"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repo-opener"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/repo-opener"]
    end
  end

  # No zap stanza required

end
