# This file was generated by GoReleaser. DO NOT EDIT.
cask "srekit" do
  version "0.32.0"

  on_macos do
    on_intel do
      sha256 "0a4ef4ad4f90d44533e86c7a125065069d9eda969c856c6291d70cb409e4f62a"
      url "https://github.com/jtprogru/srekit/releases/download/v#{version}/srekit_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "930ffc7e9b2c46304c6c1783b65292576126222c32fb7b6c5008336c3820a68f"
      url "https://github.com/jtprogru/srekit/releases/download/v#{version}/srekit_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "eadd82cbbe97a945db2909d7045128606136a7fbc76d43a2904b249901dcea2f"
      url "https://github.com/jtprogru/srekit/releases/download/v#{version}/srekit_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "82ba2c56db3826d3d1f246a521012e07a3a8fb1aeb7d8a9289a14ae6cf975692"
      url "https://github.com/jtprogru/srekit/releases/download/v#{version}/srekit_Linux_arm64.tar.gz"
    end
  end

  name "srekit"
  desc "Generator of SRE text artifacts: tasks, postmortems, runbooks, RFCs, on-call reports, SLOs, error budget policies, changelogs"
  homepage "https://github.com/jtprogru/srekit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "srekit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/srekit"]
    end
  end

  # No zap stanza required

end
