# This file was generated by GoReleaser. DO NOT EDIT.
cask "srekit" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "3e21cf9eaea8a3a4e8757badf61fdeed7809af74e99958e3e68edf43d3afad7d"
      url "https://github.com/jtprogru/srekit/releases/download/v#{version}/srekit_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "366bfbdcf18cc81b7839620607decbcf3cf39a85f427d328744c029904448f22"
      url "https://github.com/jtprogru/srekit/releases/download/v#{version}/srekit_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "76199be0231b9d854f78d93f77b822126247b7536c4058ac17e6ae214f116d89"
      url "https://github.com/jtprogru/srekit/releases/download/v#{version}/srekit_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f1fd48c71f58854f4a022a0272b7b9494ffefb9195d804e6fd0c6f73348856b1"
      url "https://github.com/jtprogru/srekit/releases/download/v#{version}/srekit_Linux_arm64.tar.gz"
    end
  end

  name "srekit"
  desc "Generator of SRE text artifacts: tasks, licenses, postmortems, RFCs"
  homepage "https://github.com/jtprogru/srekit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "srekit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/srekit"]
    end
  end

  # No zap stanza required

end
