# This file was generated by GoReleaser. DO NOT EDIT.
cask "srekit" do
  version "0.30.0"

  on_macos do
    on_intel do
      sha256 "a2ef68a66514edd2ed3c933a5bbd5e6a321e2795155ae61d58f474195e2ed788"
      url "https://github.com/jtprogru/srekit/releases/download/v#{version}/srekit_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "047616afbe51a20245fc84ebbc014e2306b68dcd1eea143ac978a8d5e9d41064"
      url "https://github.com/jtprogru/srekit/releases/download/v#{version}/srekit_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8bd251fdca4dc43eaac37c995b539f8e88d6fc4403744ba4eedb736847d0d6d9"
      url "https://github.com/jtprogru/srekit/releases/download/v#{version}/srekit_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7dd5e3ed8474e7a359300c042a907330d2bdd4f141e0e8eec5e92a00507e9c62"
      url "https://github.com/jtprogru/srekit/releases/download/v#{version}/srekit_Linux_arm64.tar.gz"
    end
  end

  name "srekit"
  desc "Generator of SRE text artifacts: tasks, postmortems, runbooks, RFCs, on-call reports, SLOs, error budget policies, changelogs"
  homepage "https://github.com/jtprogru/srekit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "srekit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/srekit"]
    end
  end

  # No zap stanza required

end
