# This file was generated by GoReleaser. DO NOT EDIT.
cask "thingsexporter" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "cdc1731d8242ff689768f97e1117ca30697616d764fb3b3b56b969422ffc9df5"
      url "https://github.com/jtprogru/thingsexporter/releases/download/v#{version}/thingsexporter_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/jtprogru/thingsexporter"
    end
    on_arm do
      sha256 "dd599e9b213aea48db43c91eda50abf56597feecc51cd7c18645978645a9388b"
      url "https://github.com/jtprogru/thingsexporter/releases/download/v#{version}/thingsexporter_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/jtprogru/thingsexporter"
    end
  end

  on_linux do
    on_intel do
      sha256 "e782e424d0bb1b8b2e80319ea662c90be569102a0a6e715caefda5e089fa5c41"
      url "https://github.com/jtprogru/thingsexporter/releases/download/v#{version}/thingsexporter_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/jtprogru/thingsexporter"
    end
    on_arm do
      sha256 "e2d9aa21f551cb2c17c367fb665e76a1003a0763a52cd6a8a5dc9e430651935a"
      url "https://github.com/jtprogru/thingsexporter/releases/download/v#{version}/thingsexporter_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/jtprogru/thingsexporter"
    end
  end

  name "thingsexporter"
  desc "Export Things 3 SQLite database to JSON or Markdown"
  homepage "https://github.com/jtprogru/thingsexporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "thingsexporter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/thingsexporter"]
    end
  end

  # No zap stanza required

end
