# This file was generated by GoReleaser. DO NOT EDIT.
cask "things" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "8e5ee2135db94bdffb412a8ab770c17d41e30df7aa86deae70f57afedfe44125"
      url "https://github.com/jtprogru/thingscli/releases/download/v#{version}/thingscli_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b5c608e84424d1da1ec9b3128cfbb93531974f4aada8065438e177f280afbc50"
      url "https://github.com/jtprogru/thingscli/releases/download/v#{version}/thingscli_Darwin_x86_64.tar.gz"
    end
  end

  name "things"
  desc "CLI for Things 3 via AppleScript with runtime-probed multi-locale support"
  homepage "https://github.com/jtprogru/thingscli"

  livecheck do
    skip "Auto-generated on release."
  end

  # thingscli ходит в Things 3 через AppleScript, портируемого фолбэка нет.
  depends_on macos: :big_sur

  binary "things"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/things"]
  end

  # No zap stanza required
end
