# This file was generated by GoReleaser. DO NOT EDIT.
cask "thingsexporter" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "eab41ae01e816928e2f7435a6f8fcbe6cd0aea6890a36394f5882c4a38283911"
      url "https://github.com/jtprogru/thingsexporter/releases/download/v#{version}/thingsexporter_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f5928ea73ca5c50fb38553ee5ec095a28e4e2629bff40d289497a87e761b0e4b"
      url "https://github.com/jtprogru/thingsexporter/releases/download/v#{version}/thingsexporter_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c79f689eaef8df360b75af29e60b43bf276d2ec20e159ccf48ee001c0f6dde33"
      url "https://github.com/jtprogru/thingsexporter/releases/download/v#{version}/thingsexporter_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2a2812f7a7cba3c17d112e087cf1971b9f71ef45f55be30a62de9120a924277a"
      url "https://github.com/jtprogru/thingsexporter/releases/download/v#{version}/thingsexporter_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "thingsexporter"
  desc "Export Things 3 SQLite database to JSON or Markdown"
  homepage "https://github.com/jtprogru/thingsexporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "thingsexporter"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/thingsexporter"]
  end

  # No zap stanza required
end
