# This file was generated by GoReleaser. DO NOT EDIT.
cask "todushka" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "6b6e2bc63d4350b96fe3295a5f854d44c890af82c8616339d9f7c502b11ff5db"
      url "https://github.com/jtprogru/todushka/releases/download/v#{version}/todushka_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/jtprogru/todushka"
    end
    on_arm do
      sha256 "1cce862e1cb6ff7d4a4b461c99dfc96036b218ac79a33dc41bec9cd76fc24854"
      url "https://github.com/jtprogru/todushka/releases/download/v#{version}/todushka_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/jtprogru/todushka"
    end
  end

  on_linux do
    on_intel do
      sha256 "c286faba82e06e3478629f495195c247cc48c4a3bc7edda6f807247e37a264ee"
      url "https://github.com/jtprogru/todushka/releases/download/v#{version}/todushka_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/jtprogru/todushka"
    end
    on_arm do
      sha256 "1225e78127f2ffe00ab5bf6f33a6054b2c0c3fb66ef8c184f743312455a06373"
      url "https://github.com/jtprogru/todushka/releases/download/v#{version}/todushka_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/jtprogru/todushka"
    end
  end

  name "todushka"
  desc "Terminal Things 3: a keyboard-first TUI todo manager with Inbox / Today / Upcoming workflow and embedded local store"
  homepage "https://github.com/jtprogru/todushka"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "todushka"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/todushka"]
    end
  end

  # No zap stanza required

end
