# This file was generated by GoReleaser. DO NOT EDIT.
cask "todushka" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "07f37483ffa0188a738f269157ee59a7138eca467448dcec01d2fc592d6dbcf1"
      url "https://github.com/jtprogru/todushka/releases/download/v#{version}/todushka_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/jtprogru/todushka"
    end
    on_arm do
      sha256 "3cfb9c4249df1bf049e245f283e7c5b54731b803c9325f9e7cf71588ee740167"
      url "https://github.com/jtprogru/todushka/releases/download/v#{version}/todushka_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/jtprogru/todushka"
    end
  end

  on_linux do
    on_intel do
      sha256 "230c0b7e9dce7cb09325c5cb9a983d0955180cd86c73995321701d53ed35ee7c"
      url "https://github.com/jtprogru/todushka/releases/download/v#{version}/todushka_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/jtprogru/todushka"
    end
    on_arm do
      sha256 "6396489685dc2082651e7ff326ef87c1a17c1a0149617c3bf6f26f146e5a241b"
      url "https://github.com/jtprogru/todushka/releases/download/v#{version}/todushka_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/jtprogru/todushka"
    end
  end

  name "todushka"
  desc "Terminal Things 3: a keyboard-first TUI todo manager with Inbox / Today / Upcoming workflow and embedded local store"
  homepage "https://github.com/jtprogru/todushka"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "todushka"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/todushka"]
    end
  end

  # No zap stanza required

end
