# This file was generated by GoReleaser. DO NOT EDIT.
cask "todushka" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "4107dc6d6e9cd27b5628f617a0f1fa7790049cf7318b86d142967592eb691cfd"
      url "https://github.com/jtprogru/todushka/releases/download/v#{version}/todushka_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/jtprogru/todushka"
    end
    on_arm do
      sha256 "e3929f7ea98bdb209efaaf1827cfb079f2720b6bd8cb89bd114eef23db5fd195"
      url "https://github.com/jtprogru/todushka/releases/download/v#{version}/todushka_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/jtprogru/todushka"
    end
  end

  on_linux do
    on_intel do
      sha256 "96f5a5070a7ad4f2dab294663feb7a81b43c5f8277284195a968d7ab23b37863"
      url "https://github.com/jtprogru/todushka/releases/download/v#{version}/todushka_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/jtprogru/todushka"
    end
    on_arm do
      sha256 "8e27f7e934c43c0f31bc0b47e39e08a7811cd1f37523fe83775d43069fdb3108"
      url "https://github.com/jtprogru/todushka/releases/download/v#{version}/todushka_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/jtprogru/todushka"
    end
  end

  name "todushka"
  desc "Terminal Things 3: a keyboard-first TUI todo manager with Inbox / Today / Upcoming workflow and embedded local store"
  homepage "https://github.com/jtprogru/todushka"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "todushka"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/todushka"]
    end
  end

  # No zap stanza required

end
