# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoMonkill < Formula
  desc "Run a command after a process with a given PID terminates"
  homepage "https://github.com/jtprogru/go-monkill"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jtprogru/go-monkill/releases/download/v0.3.0/go-monkill_Darwin_x86_64.tar.gz"
      sha256 "e982f346d61f43356a0856bc004a9dba6b8397f0140b577e1eac20708179aec5"

      define_method(:install) do
        bin.install "go-monkill"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jtprogru/go-monkill/releases/download/v0.3.0/go-monkill_Darwin_arm64.tar.gz"
      sha256 "7761ca455337af9a647fab94407588f7cd38993e623ad7365b4aebec48913782"

      define_method(:install) do
        bin.install "go-monkill"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtprogru/go-monkill/releases/download/v0.3.0/go-monkill_Linux_x86_64.tar.gz"
      sha256 "8535b9ca161851b6943bed2aa71a2f111c648233e24c60ce66db29394dce22ff"
      define_method(:install) do
        bin.install "go-monkill"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtprogru/go-monkill/releases/download/v0.3.0/go-monkill_Linux_arm64.tar.gz"
      sha256 "4ee82cf8b04f81245150fc47e2efe51287b9981e6f39fd4e202ffc1ee80d13fe"
      define_method(:install) do
        bin.install "go-monkill"
      end
    end
  end

  test do
    system "#{bin}/go-monkill", "version"
  end
end
