# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoMonkill < Formula
  desc "Run a command after a process with a given PID terminates"
  homepage "https://github.com/jtprogru/go-monkill"
  version "0.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jtprogru/go-monkill/releases/download/v0.6.0/go-monkill_Darwin_x86_64.tar.gz"
      sha256 "e7388e18706cca95cc738effa1243de23f28647dfe006b37e5251ba176cd9f12"

      define_method(:install) do
        bin.install "go-monkill"
        bash_completion.install "completions/go-monkill.bash" => "go-monkill"
        zsh_completion.install  "completions/go-monkill.zsh"  => "_go-monkill"
        fish_completion.install "completions/go-monkill.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jtprogru/go-monkill/releases/download/v0.6.0/go-monkill_Darwin_arm64.tar.gz"
      sha256 "8e35911c78bb0ffd8dabcaf30cc5b24094363bd9840d458e3397879cd46e0b36"

      define_method(:install) do
        bin.install "go-monkill"
        bash_completion.install "completions/go-monkill.bash" => "go-monkill"
        zsh_completion.install  "completions/go-monkill.zsh"  => "_go-monkill"
        fish_completion.install "completions/go-monkill.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtprogru/go-monkill/releases/download/v0.6.0/go-monkill_Linux_x86_64.tar.gz"
      sha256 "eb7aaf4fa8054cbbe852f467a99bc44a55f30834c02d49421a7abad92f71831a"
      define_method(:install) do
        bin.install "go-monkill"
        bash_completion.install "completions/go-monkill.bash" => "go-monkill"
        zsh_completion.install  "completions/go-monkill.zsh"  => "_go-monkill"
        fish_completion.install "completions/go-monkill.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtprogru/go-monkill/releases/download/v0.6.0/go-monkill_Linux_arm64.tar.gz"
      sha256 "21e983f646b4fd5884e7d99cc706ffb3cddbf117c737ff57806b404c5c26643e"
      define_method(:install) do
        bin.install "go-monkill"
        bash_completion.install "completions/go-monkill.bash" => "go-monkill"
        zsh_completion.install  "completions/go-monkill.zsh"  => "_go-monkill"
        fish_completion.install "completions/go-monkill.fish"
      end
    end
  end

  test do
    system "#{bin}/go-monkill", "version"
  end
end
