# typed: false
# frozen_string_literal: true

# This file is generated by .github/workflows/release.yml in jtprogru/jlic
# from .github/templates/jlic.rb.tpl. Do not edit by hand.
class Jlic < Formula
  desc "Generate LICENSE files for open source projects"
  homepage "https://github.com/jtprogru/jlic"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jtprogru/jlic/releases/download/v0.2.1/jlic-v0.2.1-aarch64-apple-darwin.tar.gz"
      sha256 "9c0ea93ce58958c7f4126f2474a1eedd32e15f17c56cbb07eecd97d73e63e7f1"
    else
      url "https://github.com/jtprogru/jlic/releases/download/v0.2.1/jlic-v0.2.1-x86_64-apple-darwin.tar.gz"
      sha256 "4faefd40372186191cad672ca8eaa83a16afd5c7f3e82e3740e006ab4e8dbc07"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtprogru/jlic/releases/download/v0.2.1/jlic-v0.2.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "105b3b694cab2dcb5cf7489ef20a6dfbcee2a4e2ad3aa13ccc6f35746bc959ad"
    else
      url "https://github.com/jtprogru/jlic/releases/download/v0.2.1/jlic-v0.2.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "04acf86199dbd5680f6adfbcd034fff9ecf071ae1bddadb8cbd9401a3264737b"
    end
  end

  def install
    bin.install "jlic"
    man1.install "man/jlic.1" if File.exist?("man/jlic.1")
    if File.directory?("completions")
      bash_completion.install "completions/jlic.bash" => "jlic"
      zsh_completion.install "completions/jlic.zsh" => "_jlic"
      fish_completion.install "completions/jlic.fish"
    end
  end

  test do
    system "#{bin}/jlic", "--version"
    system "#{bin}/jlic", "mit", "--stdout", "--name", "Test"
  end
end
