# typed: false
# frozen_string_literal: true

# This file is generated by .github/workflows/release.yml in jtprogru/jlic
# from .github/templates/jlic.rb.tpl. Do not edit by hand.
class Jlic < Formula
  desc "Generate LICENSE files for open source projects"
  homepage "https://github.com/jtprogru/jlic"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jtprogru/jlic/releases/download/v0.2.0/jlic-v0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "9e83e4ac960550148bfedd8beee0cd84540d0a24b24cadc4fc92314d55c8c10b"
    else
      url "https://github.com/jtprogru/jlic/releases/download/v0.2.0/jlic-v0.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "c499d56db908dae80a3e5d7ca9d5fb6b871fc9f026e64fb7d152563ba7859611"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtprogru/jlic/releases/download/v0.2.0/jlic-v0.2.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "44e550f8607f7887643ec3761710203a5e16ce7299f488b033eaf693b85e678c"
    else
      url "https://github.com/jtprogru/jlic/releases/download/v0.2.0/jlic-v0.2.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "75b6d980bb24815cfcd0ef4ba026aa688e0c2fdbd24c31cdca529aa39e03ab6e"
    end
  end

  def install
    bin.install "jlic"
    man1.install "man/jlic.1" if File.exist?("man/jlic.1")
    if File.directory?("completions")
      bash_completion.install "completions/jlic.bash" => "jlic"
      zsh_completion.install "completions/jlic.zsh" => "_jlic"
      fish_completion.install "completions/jlic.fish"
    end
  end

  test do
    system "#{bin}/jlic", "--version"
    system "#{bin}/jlic", "mit", "--stdout", "--name", "Test"
  end
end
