# typed: false
# frozen_string_literal: true

# This file is generated by .github/workflows/release.yml in
# jtprogru/jlic. Do not edit by hand.
class Jlic < Formula
  desc "Generate LICENSE files for open source projects"
  homepage "https://github.com/jtprogru/jlic"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jtprogru/jlic/releases/download/v0.1.0/jlic-v0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "9562b54522a460fc8c99d9469b31c6aaab66e4d8c0d865d4d1a24c4a068fb9e8"
    else
      url "https://github.com/jtprogru/jlic/releases/download/v0.1.0/jlic-v0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "395e30ab3390d1984be2a1d4d25e9be9e579c15161670d14f118da5623dfc9c8"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtprogru/jlic/releases/download/v0.1.0/jlic-v0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "01dd88797d0ac079fac2f8ef17e6577551502cb5f41f5894d258a6771b0a56f0"
    else
      url "https://github.com/jtprogru/jlic/releases/download/v0.1.0/jlic-v0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "0b3c0ea6635772c5043c497e332fcd494aaacddd6489f2c3c2255549353e210e"
    end
  end

  def install
    bin.install "jlic"
    man1.install "man/jlic.1" if File.exist?("man/jlic.1")
    if File.directory?("completions")
      bash_completion.install "completions/jlic.bash" => "jlic"
      zsh_completion.install "completions/jlic.zsh" => "_jlic"
      fish_completion.install "completions/jlic.fish"
    end
  end

  test do
    system "#{bin}/jlic", "--version"
    system "#{bin}/jlic", "mit", "--stdout", "--name", "Test"
  end
end
