# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jtpost < Formula
  desc "CLI/web-сервис для управления публикациями в Telegram-канал."
  homepage "https://github.com/jtprogru/jtpost"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jtprogru/jtpost/releases/download/v0.4.0/jtpost_Darwin_x86_64.tar.gz"
      sha256 "5bb9d6c7023688e4dad48a30e88d5307b6d4a8e9b721ffffa3f7c18473c2da29"

      define_method(:install) do
        bin.install "jtpost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jtprogru/jtpost/releases/download/v0.4.0/jtpost_Darwin_arm64.tar.gz"
      sha256 "a962b51ef2ab666ed2ae13484cbbadd0d76c25d231f70855180c44043e3a3509"

      define_method(:install) do
        bin.install "jtpost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtprogru/jtpost/releases/download/v0.4.0/jtpost_Linux_x86_64.tar.gz"
      sha256 "1b767e90a9a0679a285a83edd998983eea269dc8a45c85ea6c894ec7a53257c7"
      define_method(:install) do
        bin.install "jtpost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtprogru/jtpost/releases/download/v0.4.0/jtpost_Linux_arm64.tar.gz"
      sha256 "ce747a88e45500a788bd1987d326cb88b9ab306798c54e6811b9ba6dfc1a184f"
      define_method(:install) do
        bin.install "jtpost"
      end
    end
  end

  test do
    system "#{bin}/jtpost", "version"
  end
end
