# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jtpost < Formula
  desc "CLI/web-сервис для управления публикациями в Telegram-канал."
  homepage "https://github.com/jtprogru/jtpost"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jtprogru/jtpost/releases/download/v0.5.1/jtpost_Darwin_x86_64.tar.gz"
      sha256 "4ede46995e2ab7e3cc4946a203aca56fdf6560c42e994ae11703090ced04d9e3"

      define_method(:install) do
        bin.install "jtpost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jtprogru/jtpost/releases/download/v0.5.1/jtpost_Darwin_arm64.tar.gz"
      sha256 "40468b6e516ee45c822ec8fcb51999f25cd8c56afd202bdee83b4145c7dd1409"

      define_method(:install) do
        bin.install "jtpost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtprogru/jtpost/releases/download/v0.5.1/jtpost_Linux_x86_64.tar.gz"
      sha256 "51f61f39129f3edd72351424c611c953098945fec3ec47f3ce5cd5d43923e17e"
      define_method(:install) do
        bin.install "jtpost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtprogru/jtpost/releases/download/v0.5.1/jtpost_Linux_arm64.tar.gz"
      sha256 "450e6df363542ad8954c724b4157337321aa9cbb267a7a22e0cbaa1f307af972"
      define_method(:install) do
        bin.install "jtpost"
      end
    end
  end

  test do
    system "#{bin}/jtpost", "version"
  end
end
