# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Noisy < Formula
  desc "Random HTTP/DNS traffic noise generator (Go port of 1tayH/noisy)"
  homepage "https://github.com/jtprogru/noisy"
  version "0.2.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jtprogru/noisy/releases/download/v0.2.0/noisy_Darwin_x86_64.tar.gz"
      sha256 "269c3b0f2e8be43a96d56560c209e4128dd000d95bed27f0d846f60fa711f148"

      define_method(:install) do
        bin.install "noisy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jtprogru/noisy/releases/download/v0.2.0/noisy_Darwin_arm64.tar.gz"
      sha256 "fe2871d7bfeee2c8a940b88adcd8bc065c061a545e1dc865e016486611d8449f"

      define_method(:install) do
        bin.install "noisy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtprogru/noisy/releases/download/v0.2.0/noisy_Linux_x86_64.tar.gz"
      sha256 "c9776f19c7bc5ec6c2c837319c8fdd5849aa2b29e98111f304e4abbe4ca92bd4"
      define_method(:install) do
        bin.install "noisy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtprogru/noisy/releases/download/v0.2.0/noisy_Linux_arm64.tar.gz"
      sha256 "495bd03b68a5a42ed7f870d96a6d903c70cbfe245ec37c1c3700b945ebc47254"
      define_method(:install) do
        bin.install "noisy"
      end
    end
  end

  test do
    system "#{bin}/noisy", "version"
  end
end
