# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Passgen < Formula
  desc "Password generator with configurable character classes and memorable mode"
  homepage "https://github.com/jtprogru/jtgpwgen"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jtprogru/jtgpwgen/releases/download/v0.1.0/passgen_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "a692415f9ed8d3dfbdb55fe75988e24cc09a1841facd30bf4d24ddc0931457ee"

      define_method(:install) do
        bin.install "passgen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jtprogru/jtgpwgen/releases/download/v0.1.0/passgen_0.1.0_Darwin_arm64.tar.gz"
      sha256 "b24b283141f3404e7cbf42b7917441303c466c5035782fb18c5604461f02c5b3"

      define_method(:install) do
        bin.install "passgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtprogru/jtgpwgen/releases/download/v0.1.0/passgen_0.1.0_Linux_x86_64.tar.gz"
      sha256 "cb236e4cdb1b10494ee9a91286e6a0a43aa7d924c75de80f03227e206ef57a33"
      define_method(:install) do
        bin.install "passgen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtprogru/jtgpwgen/releases/download/v0.1.0/passgen_0.1.0_Linux_arm64.tar.gz"
      sha256 "d09f5948bc82253bf505ca2873fda02451d532b870b73ed235e87bb88c3f97f4"
      define_method(:install) do
        bin.install "passgen"
      end
    end
  end

  test do
    assert_match "passgen", shell_output("#{bin}/passgen --help")
  end
end
