# typed: false
# frozen_string_literal: true

# This file is generated by .github/workflows/release.yml in
# jtprogru/rspassimpt. Do not edit by hand.
class Rspassimpt < Formula
  desc "Import passwords from a macOS Passwords CSV export into pass"
  homepage "https://github.com/jtprogru/rspassimpt"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jtprogru/rspassimpt/releases/download/v0.1.0/rspassimpt-v0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "240bc5de1c5ffb862975aed335a895dd8ba8004230a03bc47c14ca8c22f8b460"
    else
      url "https://github.com/jtprogru/rspassimpt/releases/download/v0.1.0/rspassimpt-v0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "d86f40d6c1a6478451fd96dca0b55e8b49847dc560a3cc44e760b662f5a9f59c"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtprogru/rspassimpt/releases/download/v0.1.0/rspassimpt-v0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "faffe88b1b67f4aefb3fa05edc7afd5da7750bfefd85e71d6be1f418754414fe"
    else
      url "https://github.com/jtprogru/rspassimpt/releases/download/v0.1.0/rspassimpt-v0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "b094d9c170b30d9376561dbc92efff2e4440e431389973c3601f11be58b934e4"
    end
  end

  depends_on "gnupg"
  depends_on "pass"

  def install
    bin.install "rspassimpt"
  end

  test do
    system "#{bin}/rspassimpt", "--version"
  end
end
