# typed: false
# frozen_string_literal: true

# This file is generated by .github/workflows/release.yml in
# jtprogru/tgselector. Do not edit by hand.
class Tgselector < Formula
  desc "Extract and process posts from a Telegram JSON export by id"
  homepage "https://github.com/jtprogru/tgselector"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jtprogru/tgselector/releases/download/v0.1.0/tgselector-v0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "97b83cb65747bb94f797a14f3dccbb019a857e777dcf4639a85ec260979b32fb"
    else
      url "https://github.com/jtprogru/tgselector/releases/download/v0.1.0/tgselector-v0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "24d63b957bb26446cbbedf0cb164b8d600352c72745edccfb22c3b200688d529"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtprogru/tgselector/releases/download/v0.1.0/tgselector-v0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "be0c981be078354651200f94e84f03db1409ee9fac698404c53697ca13e66573"
    else
      url "https://github.com/jtprogru/tgselector/releases/download/v0.1.0/tgselector-v0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "17e4e2755527a3365b805551e809e3cd8cb6f01fa98c3a543576c38a00b469f8"
    end
  end

  def install
    bin.install "tgselector"
    # Generate shell completions from the binary itself.
    generate_completions_from_executable(bin/"tgselector", "--completions")
  end

  test do
    system "#{bin}/tgselector", "--version"
  end
end
